// Core rasterization + orchestration for tree-mask auto-generation.
//
// Produces up to 6 layers, keyed (source, band) for source in {osm, canopy}
// and band in {low, medium, tall} (or however many bands are configured):
//   1. OSM tree points and wood/forest polygons are painted first. Each
//      pixel's height band comes from sampling the canopy-height grid at
//      that location (or a flat default if canopy data is disabled/
//      unavailable) - written into osm-<band> layers, and every touched
//      pixel is marked in a shared OSM-coverage mask.
//   2. Canopy-height-only fallback fills canopy-<band> layers, but ONLY for
//      pixels NOT in the OSM-coverage mask - a hard exclusion, not a
//      priority tiebreak: canopy fallback never paints anywhere OSM has
//      already claimed, even though canopy data was itself used as a value
//      source for those OSM-claimed pixels.
// Species per layer are weighted automatically from CGLS-LC100 forest-type
// class + latitude, sampled at the same per-pixel locations.
import path from 'path';
import { randomUUID } from 'crypto';
import { buildPolygonIndex } from '../spatialIndex.js';
import { downloadPlantAsset, getAvailablePlants } from '../cache/plants.js';
import { fetchTreeOsmData, projectTreePointsToMask, projectWoodPolygonsToMask } from './osmTreeData.js';
import { fetchCanopyHeightGrid, fetchLandCoverGrid } from './canopyData.js';
import { openProject, replaceAutoGeneratedTreeLayers } from '../project.js';
import { broadcast } from '../window.js';
import { DEFAULT_MASK_SIZE, RESOURCES_FILE_PROTOCOL } from '../../constants.js';

export const DEFAULT_BAND_THRESHOLDS = [
  { id: 'low', label: 'Low', max: 4 },
  { id: 'medium', label: 'Medium', max: 12 },
  { id: 'tall', label: 'Tall', max: Infinity },
];

export const DEFAULT_SCALE_RANGE_BY_BAND = {
  low: { min: 0.4, max: 0.8 },
  medium: { min: 0.8, max: 1.3 },
  tall: { min: 1.3, max: 2.0 },
};

export const DEFAULT_BASELINE_DENSITY_BY_SOURCE = { osm: 0.3, canopy: 0.3 };

const FALLBACK_BAND_ID = 'medium';
// Below this canopy height (meters), a pixel isn't considered "forested"
// for the canopy-only fallback pass - avoids painting noise-level values.
const CANOPY_PRESENCE_THRESHOLD_M = 1;
// Canopy height at/above which fallback density saturates to max (255).
const CANOPY_REFERENCE_HEIGHT_M = 15;
const CANOPY_MIN_DENSITY_BYTE = 40;

// CGLS-LC100 Forest-Type-layer class codes, verified against the product's
// published band legend: 0 Unknown, 1 Evergreen needleleaf,
// 2 Evergreen broadleaf, 3 Deciduous needleleaf, 4 Deciduous broadleaf,
// 5 Mixed.
const FOREST_TYPE = {
  UNKNOWN: 0,
  EVERGREEN_NEEDLELEAF: 1,
  EVERGREEN_BROADLEAF: 2,
  DECIDUOUS_NEEDLELEAF: 3,
  DECIDUOUS_BROADLEAF: 4,
  MIXED: 5,
};

// Maps CGLS forest-type classes onto weights over the 5 fixed catalog
// species (src/lib/cache/plants.js: ash-v1, pine-v1, willow-v1, aspen-v1,
// palm-v1). This is a judgment call, not a verifiable fact - kept as a
// small, easily-retuned lookup rather than baked into the algorithm.
function baseSpeciesWeightsForClass(forestTypeClass) {
  switch (forestTypeClass) {
    case FOREST_TYPE.EVERGREEN_NEEDLELEAF:
      return { 'pine-v1': 0.9, 'ash-v1': 0.1 };
    case FOREST_TYPE.DECIDUOUS_NEEDLELEAF:
      return { 'pine-v1': 0.6, 'aspen-v1': 0.4 };
    case FOREST_TYPE.EVERGREEN_BROADLEAF:
      return { 'willow-v1': 0.5, 'ash-v1': 0.5 };
    case FOREST_TYPE.DECIDUOUS_BROADLEAF:
      return { 'ash-v1': 0.5, 'aspen-v1': 0.5 };
    case FOREST_TYPE.MIXED:
      return { 'ash-v1': 0.3, 'pine-v1': 0.3, 'aspen-v1': 0.2, 'willow-v1': 0.2 };
    case FOREST_TYPE.UNKNOWN:
    default:
      return { 'ash-v1': 1 };
  }
}

// Refines class-based weights with latitude: broadleaf-evergreen/mixed
// forest near the equator leans tropical (palm-like) rather than temperate.
export function speciesWeightsForClass(forestTypeClass, latitude) {
  const weights = { ...baseSpeciesWeightsForClass(forestTypeClass) };
  const absLat = Math.abs(latitude ?? 90);
  const isTropicalCandidate = forestTypeClass === FOREST_TYPE.EVERGREEN_BROADLEAF || forestTypeClass === FOREST_TYPE.MIXED;
  if (isTropicalCandidate && absLat < 30) {
    const palmWeight = ((30 - absLat) / 30) * 0.6; // up to 0.6 at the equator, 0 at 30 degrees
    const scale = 1 - palmWeight;
    for (const key of Object.keys(weights)) weights[key] *= scale;
    weights['palm-v1'] = (weights['palm-v1'] || 0) + palmWeight;
  }
  return weights;
}

export function bandFromHeight(heightMeters, bandThresholds) {
  for (const band of bandThresholds) {
    if (heightMeters <= band.max) return band.id;
  }
  return bandThresholds[bandThresholds.length - 1].id;
}

function heightToDensityByte(heightMeters) {
  const t = Math.min(1, heightMeters / CANOPY_REFERENCE_HEIGHT_M);
  return Math.round(CANOPY_MIN_DENSITY_BYTE + t * (255 - CANOPY_MIN_DENSITY_BYTE));
}

// Paints a filled circle of `value` (0-255) into a sparse pixel map
// (Map<pixelIndex, value>), clamped to the mask bounds, and records every
// touched pixel index into `touchedIndices` (used for the OSM-coverage
// mask). A tunable radius lets a single OSM tree point render as more than
// a lone pixel - @opengolfsim/fuse's plantFromMask treats density
// probabilistically per pixel, so an isolated 1px point often yields zero
// trees.
export function paintTreePointCircle(pixelMap, px, py, radiusPx, maskSize, value = 255, touchedIndices) {
  const cx = Math.round(px);
  const cy = Math.round(py);
  const r = Math.max(0, Math.round(radiusPx));
  const r2 = r * r;
  for (let dy = -r; dy <= r; dy++) {
    const y = cy + dy;
    if (y < 0 || y >= maskSize) continue;
    for (let dx = -r; dx <= r; dx++) {
      if (dx * dx + dy * dy > r2) continue;
      const x = cx + dx;
      if (x < 0 || x >= maskSize) continue;
      const i = y * maskSize + x;
      const existing = pixelMap.get(i) || 0;
      if (value > existing) pixelMap.set(i, value);
      if (touchedIndices) touchedIndices.push(i);
    }
  }
}

// Returns every mask pixel index whose center falls inside the polygon,
// iterating only the polygon's own bounding box (clamped to the mask) and
// using buildPolygonIndex for containment - not a naive scan of every mask
// pixel.
function getPolygonCoveredPixels(outerRing, holeRings, maskSize) {
  if (!outerRing || outerRing.length < 3) return [];

  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const [x, y] of outerRing) {
    if (x < minX) minX = x;
    if (y < minY) minY = y;
    if (x > maxX) maxX = x;
    if (y > maxY) maxY = y;
  }
  const startX = Math.max(0, Math.floor(minX));
  const endX = Math.min(maskSize - 1, Math.ceil(maxX));
  const startY = Math.max(0, Math.floor(minY));
  const endY = Math.min(maskSize - 1, Math.ceil(maxY));
  if (startX > endX || startY > endY) return [];

  const cellSize = Math.max((maxX - minX) / 32, 1);
  const polyIndex = buildPolygonIndex(outerRing, holeRings || [], cellSize);

  const covered = [];
  for (let y = startY; y <= endY; y++) {
    for (let x = startX; x <= endX; x++) {
      if (polyIndex.isInside([x + 0.5, y + 0.5])) covered.push(y * maskSize + x);
    }
  }
  return covered;
}

function pixelMapToPositions(pixelMap) {
  return [...pixelMap.entries()].map(([i, val]) => ({ i, val }));
}

function pixelToLonLat(i, maskSize, bounds, size) {
  const x = i % maskSize;
  const y = Math.floor(i / maskSize);
  const scale = size / maskSize;
  const mmX = (x + 0.5) * scale;
  const mmY = (y + 0.5) * scale;
  const lon = bounds.west + (mmX / size) * (bounds.east - bounds.west);
  const lat = bounds.north - (mmY / size) * (bounds.north - bounds.south);
  return { lon, lat };
}

// Accumulates per-(source,band) pixel density and species weight totals as
// pixels get assigned, so each output layer's treeConfigs can be built from
// an average of the land-cover-driven weights sampled across its pixels.
function createAccumulators() {
  const bySourceBand = new Map();
  return {
    get(source, bandId) {
      const key = `${source}-${bandId}`;
      if (!bySourceBand.has(key)) {
        bySourceBand.set(key, { source, bandId, pixelMap: new Map(), speciesWeightTotals: new Map(), sampleCount: 0 });
      }
      return bySourceBand.get(key);
    },
    values() {
      return [...bySourceBand.values()];
    },
  };
}

function accumulateSpeciesWeights(accumulator, weights) {
  accumulator.sampleCount++;
  for (const [id, weight] of Object.entries(weights)) {
    accumulator.speciesWeightTotals.set(id, (accumulator.speciesWeightTotals.get(id) || 0) + weight);
  }
}

// Ensures a catalog species' asset is downloaded/cached, and returns a
// treeConfig object in the same shape src/lib/cache/plants.js's
// importPlantAsset() produces - so generated layers are indistinguishable,
// to every existing consumer, from hand-configured ones.
async function ensureSpeciesConfig(speciesId, overrides = {}) {
  const catalog = getAvailablePlants();
  const entry = [...catalog.trees, ...catalog.grasses].find((t) => t.id === speciesId);
  if (!entry) throw new Error(`Unknown species id: ${speciesId}`);

  const updatedCatalog = await downloadPlantAsset(entry);
  const cached = [...updatedCatalog.trees, ...updatedCatalog.grasses].find((t) => t.id === speciesId);
  if (!cached?._cache?.filePath) throw new Error(`Failed to cache species asset: ${speciesId}`);

  return {
    id: randomUUID(),
    url: `${RESOURCES_FILE_PROTOCOL}://plant-cache/${path.basename(cached._cache.filePath)}`,
    filePath: cached._cache.filePath,
    name: cached.title,
    randomSeed: 12345,
    minDistance: 5,
    ...overrides,
  };
}

// Builds the treeConfigs array for one layer from its accumulated species
// weights: normalizes weights to fractions, then scales a baseline total
// density across them so the overall planting density stays constant
// regardless of how many species ended up mixed into the layer.
async function buildTreeConfigsForAccumulator(accumulator, scaleRange, baselineDensity, fallbackSpeciesId) {
  let weightEntries = [...accumulator.speciesWeightTotals.entries()];
  if (!weightEntries.length) {
    weightEntries = [[fallbackSpeciesId, 1]];
  }
  const totalWeight = weightEntries.reduce((sum, [, w]) => sum + w, 0) || 1;

  const configs = [];
  for (const [speciesId, weight] of weightEntries) {
    const fraction = weight / totalWeight;
    if (fraction <= 0) continue;
    const config = await ensureSpeciesConfig(speciesId, {
      scaleRange,
      density: baselineDensity * fraction,
    });
    configs.push(config);
  }
  return configs;
}

// Combines OSM points/wood polygons and canopy/land-cover rasters into
// per-(source,band) sparse pixel maps + species-weight accumulators.
function rasterizeSources({
  bounds, size, maskSize,
  osmPoints, osmWoods,
  canopyGrid, landCoverGrid,
  pointRadiusPx, bandThresholds,
  sourcesEnabled,
}) {
  const accumulators = createAccumulators();
  const osmCoverage = new Set();

  // Canopy rasters can carry nodata/sentinel values (commonly negative, or
  // implausibly large) for cells with no data - treat anything outside a
  // plausible tree-height range as "no data" rather than letting it corrupt
  // banding/density math.
  const isValidHeight = (h) => Number.isFinite(h) && h > 0 && h < 200;
  const sampleCanopyHeight = (i) => {
    if (!canopyGrid) return null;
    const h = canopyGrid[i];
    return isValidHeight(h) ? h : null;
  };
  const sampleSpeciesWeights = (i) => {
    if (!sourcesEnabled.landCoverSpecies || !landCoverGrid) return null;
    const { lat } = pixelToLonLat(i, maskSize, bounds, size);
    return speciesWeightsForClass(landCoverGrid[i], lat);
  };

  if (sourcesEnabled.osmPoints) {
    for (const { px, py } of osmPoints) {
      const cx = Math.max(0, Math.min(maskSize - 1, Math.round(px)));
      const cy = Math.max(0, Math.min(maskSize - 1, Math.round(py)));
      const centerIndex = cy * maskSize + cx;
      const heightHere = sampleCanopyHeight(centerIndex);
      const bandId = heightHere != null ? bandFromHeight(heightHere, bandThresholds) : FALLBACK_BAND_ID;
      const accumulator = accumulators.get('osm', bandId);

      const touched = [];
      paintTreePointCircle(accumulator.pixelMap, px, py, pointRadiusPx, maskSize, 255, touched);
      for (const i of touched) osmCoverage.add(i);

      const weights = sampleSpeciesWeights(centerIndex);
      if (weights) accumulateSpeciesWeights(accumulator, weights);
    }
  }

  if (sourcesEnabled.osmWoods) {
    for (const { outerRing, holeRings } of osmWoods) {
      const covered = getPolygonCoveredPixels(outerRing, holeRings, maskSize);
      for (const i of covered) {
        const heightHere = sampleCanopyHeight(i);
        const bandId = heightHere != null ? bandFromHeight(heightHere, bandThresholds) : FALLBACK_BAND_ID;
        const accumulator = accumulators.get('osm', bandId);

        const densityValue = heightHere != null ? heightToDensityByte(heightHere) : 180;
        const existing = accumulator.pixelMap.get(i) || 0;
        if (densityValue > existing) accumulator.pixelMap.set(i, densityValue);
        osmCoverage.add(i);

        const weights = sampleSpeciesWeights(i);
        if (weights) accumulateSpeciesWeights(accumulator, weights);
      }
    }
  }

  if (sourcesEnabled.canopyFallback && canopyGrid) {
    for (let i = 0; i < canopyGrid.length; i++) {
      if (osmCoverage.has(i)) continue;
      const heightHere = sampleCanopyHeight(i);
      if (heightHere == null || heightHere <= CANOPY_PRESENCE_THRESHOLD_M) continue;

      const bandId = bandFromHeight(heightHere, bandThresholds);
      const accumulator = accumulators.get('canopy', bandId);
      accumulator.pixelMap.set(i, heightToDensityByte(heightHere));

      const weights = sampleSpeciesWeights(i);
      if (weights) accumulateSpeciesWeights(accumulator, weights);
    }
  }

  return accumulators;
}

// Top-level orchestrator, wired to IPC as `trees.generateMasks`.
export async function generateTreeMasks(options = {}) {
  const {
    pointRadiusPx = 2,
    maskSize = DEFAULT_MASK_SIZE,
    bandThresholds = DEFAULT_BAND_THRESHOLDS,
    scaleRangeByBand = DEFAULT_SCALE_RANGE_BY_BAND,
    baselineDensityBySource = DEFAULT_BASELINE_DENSITY_BY_SOURCE,
    fallbackSpeciesId = 'ash-v1',
    sourcesEnabled = { osmPoints: true, osmWoods: true, canopyFallback: true, landCoverSpecies: true },
  } = options;

  const settings = openProject.settings;
  if (!settings?.bounds || !settings?.distance) {
    throw new Error('Project bounds/distance are not set - generate or import course bounds first');
  }
  const bounds = settings.bounds;
  const size = Math.round(settings.distance * 1000);
  const bbox = [bounds.south, bounds.west, bounds.north, bounds.east];

  broadcast('trees.generate.progress', { phase: 'osm-fetch', progress: 10, status: 'Fetching OSM tree data...' });
  const { points, woods } = await fetchTreeOsmData(bbox);
  const osmPoints = sourcesEnabled.osmPoints ? projectTreePointsToMask(points, bounds, size, maskSize) : [];
  const osmWoods = sourcesEnabled.osmWoods ? projectWoodPolygonsToMask(woods, bounds, size, maskSize) : [];

  let canopyGrid = null;
  if (sourcesEnabled.canopyFallback || osmPoints.length || osmWoods.length) {
    broadcast('trees.generate.progress', { phase: 'canopy-fetch', progress: 30, status: 'Fetching canopy-height data...' });
    try {
      canopyGrid = await fetchCanopyHeightGrid(bounds, maskSize);
    } catch (error) {
      console.error('Canopy-height fetch failed, continuing without it', error);
    }
  }

  let landCoverGrid = null;
  if (sourcesEnabled.landCoverSpecies) {
    broadcast('trees.generate.progress', { phase: 'landcover-fetch', progress: 50, status: 'Fetching forest-type data...' });
    try {
      landCoverGrid = await fetchLandCoverGrid(bounds, maskSize);
    } catch (error) {
      console.error('Land-cover fetch failed, falling back to a single default species', error);
    }
  }

  broadcast('trees.generate.progress', { phase: 'rasterize', progress: 65, status: 'Rasterizing tree masks...' });
  const accumulators = rasterizeSources({
    bounds, size, maskSize,
    osmPoints, osmWoods,
    canopyGrid, landCoverGrid,
    pointRadiusPx, bandThresholds,
    sourcesEnabled,
  });

  broadcast('trees.generate.progress', { phase: 'species', progress: 80, status: 'Preparing species assets...' });
  const newLayers = [];
  const nonEmpty = accumulators.values().filter((acc) => acc.pixelMap.size > 0);
  for (const accumulator of nonEmpty) {
    const band = bandThresholds.find((b) => b.id === accumulator.bandId) || bandThresholds[0];
    const scaleRange = scaleRangeByBand[accumulator.bandId] || { min: 0.6, max: 1.8 };
    const baselineDensity = baselineDensityBySource[accumulator.source] ?? 0.3;
    const treeConfigs = await buildTreeConfigsForAccumulator(accumulator, scaleRange, baselineDensity, fallbackSpeciesId);
    if (!treeConfigs.length) continue;

    const sourceLabel = accumulator.source === 'osm' ? 'OSM' : 'Canopy';
    newLayers.push({
      id: `layer-${randomUUID()}`,
      name: `Auto: ${sourceLabel} ${band.label} Trees`,
      randomSeed: 12345,
      maskSize,
      positions: pixelMapToPositions(accumulator.pixelMap),
      treeConfigs,
      _autoGenerated: true,
      _source: accumulator.source,
      _heightBand: accumulator.bandId,
    });
  }

  broadcast('trees.generate.progress', { phase: 'save', progress: 95, status: 'Saving...' });
  const updatedProject = await replaceAutoGeneratedTreeLayers(newLayers);

  broadcast('trees.generate.progress', { phase: 'complete', progress: 100, status: 'Done' });
  return {
    trees: updatedProject.trees,
    summary: {
      osmPointCount: points.length,
      osmWoodCount: woods.length,
      layersGenerated: newLayers.map((l) => ({ name: l.name, pixelCount: l.positions.length })),
    },
  };
}
